<?php

namespace Database\Seeders;

use App\Models\Township;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $townships = array(
			array('name' => 'Ahuachapán', 'state_id' => 1),
            array('name' => 'Apaneca', 'state_id' => 1),
            array('name' => 'Atiquizaya', 'state_id' => 1),
            array('name' => 'Concepción de Ataco', 'state_id' => 1),
            array('name' => 'El Refugio', 'state_id' => 1),
            array('name' => 'Guaymango', 'state_id' => 1),
            array('name' => 'Jujutla', 'state_id' => 1),
            array('name' => 'San Francisco Menéndez', 'state_id' => 1),
            array('name' => 'San Lorenzo', 'state_id' => 1),
            array('name' => 'San Pedro Puxtla', 'state_id' => 1),
            array('name' => 'Tacuba', 'state_id' => 1),
            array('name' => 'Turín', 'state_id' => 1),
            array('name' => 'Candelaria de la Frontera', 'state_id' => 2),
            array('name' => 'Chalchuapa', 'state_id' => 2),
            array('name' => 'Coatepeque', 'state_id' => 2),
            array('name' => 'El Congo', 'state_id' => 2),
            array('name' => 'El Porvenir', 'state_id' => 2),
            array('name' => 'Masahuat', 'state_id' => 2),
            array('name' => 'Metapán', 'state_id' => 2),
            array('name' => 'San Antonio Pajonal', 'state_id' => 2),
            array('name' => 'San Sebastián Salitrillo', 'state_id' => 2),
            array('name' => 'Santa Ana', 'state_id' => 2),
            array('name' => 'Santa Rosa Guachipilín', 'state_id' => 2),
            array('name' => 'Santiago de la Frontera', 'state_id' => 2),
            array('name' => 'Texistepeque', 'state_id' => 2),
            array('name' => 'Acajutla', 'state_id' => 3),
            array('name' => 'Armenia', 'state_id' => 3),
            array('name' => 'Caluco', 'state_id' => 3),
            array('name' => 'Cuisnahuat', 'state_id' => 3),
            array('name' => 'Izalco', 'state_id' => 3),
            array('name' => 'Juayúa', 'state_id' => 3),
            array('name' => 'Nahuizalco', 'state_id' => 3),
            array('name' => 'Nahulingo', 'state_id' => 3),
            array('name' => 'Salcoatitán', 'state_id' => 3),
            array('name' => 'San Antonio del Monte', 'state_id' => 3),
            array('name' => 'San Julián', 'state_id' => 3),
            array('name' => 'Santa Catarina Masahuat', 'state_id' => 3),
            array('name' => 'Santa Isabel Ishuatán', 'state_id' => 3),
            array('name' => 'Santo Domingo de Guzmán', 'state_id' => 3),
            array('name' => 'Sonsonate', 'state_id' => 3),
            array('name' => 'Sonzacate', 'state_id' => 3),
            array('name' => 'Agua Caliente', 'state_id' => 4),
            array('name' => 'Arcatao', 'state_id' => 4),
            array('name' => 'Azacualpa', 'state_id' => 4),
            array('name' => 'Cancasque', 'state_id' => 4),
            array('name' => 'Citalá', 'state_id' => 4),
            array('name' => 'Comapala', 'state_id' => 4),
            array('name' => 'Concepción Quezaltepeque', 'state_id' => 4),
            array('name' => 'Dulce Nombrre de María', 'state_id' => 4),
            array('name' => 'El Carrizal', 'state_id' => 4),
            array('name' => 'El Paraíso', 'state_id' => 4),
            array('name' => 'La Laguna', 'state_id' => 4),
            array('name' => 'La Palma', 'state_id' => 4),
            array('name' => 'La Reina', 'state_id' => 4),
            array('name' => 'Las Flores', 'state_id' => 4),
            array('name' => 'Las Vueltas', 'state_id' => 4),
            array('name' => 'Nombre de Jesús', 'state_id' => 4),
            array('name' => 'Nueva Concepción', 'state_id' => 4),
            array('name' => 'Nueva Trinidad', 'state_id' => 4),
            array('name' => 'Ojos de Agua', 'state_id' => 4),
            array('name' => 'Potonico', 'state_id' => 4),
            array('name' => 'San Antonio de la Cruz', 'state_id' => 4),
            array('name' => 'San Antonio Los Ranchos', 'state_id' => 4),
            array('name' => 'San Fernando', 'state_id' => 4),
            array('name' => 'San Francisco Lempa', 'state_id' => 4),
            array('name' => 'San Francisco Morazán', 'state_id' => 4),
            array('name' => 'San Ignacio', 'state_id' => 4),
            array('name' => 'San Isidro Labrador', 'state_id' => 4),
            array('name' => 'San Luis del Carmen', 'state_id' => 4),
            array('name' => 'San Miguel de Mercedes', 'state_id' => 4),
            array('name' => 'San Rafael', 'state_id' => 4),
            array('name' => 'Santa Rita', 'state_id' => 4),
            array('name' => 'Tejutla', 'state_id' => 4),
            array('name' => 'Playa Mizata', 'state_id' => 5),
            array('name' => 'Playa La Perla', 'state_id' => 5),
            array('name' => 'Playa El Parmarcito', 'state_id' => 5),
            array('name' => 'Playa Km 59', 'state_id' => 5),
            array('name' => 'Playa El Zonte', 'state_id' => 5),
            array('name' => 'Playa El Tunco', 'state_id' => 5),
            array('name' => 'Playa El Sunzal', 'state_id' => 5),
            array('name' => 'Playa Río Grande, La Bocana', 'state_id' => 5),
            array('name' => 'Playa El Majahual', 'state_id' => 5),
            array('name' => 'Playa San Blas', 'state_id' => 5),
            array('name' => 'Playa Conchalio', 'state_id' => 5),
            array('name' => 'Playa Punta Roca', 'state_id' => 5),
            array('name' => 'Playa La Paz', 'state_id' => 5),
            array('name' => 'Playa El Obispo', 'state_id' => 5),
            array('name' => 'Playa Las Flores', 'state_id' => 5),
            array('name' => 'Playa San Diego', 'state_id' => 5),
            array('name' => 'Aguilares', 'state_id' => 6),
            array('name' => 'Apopa', 'state_id' => 6),
            array('name' => 'Ayutuxtepeque', 'state_id' => 6),
            array('name' => 'Ciudad Delgado', 'state_id' => 6),
            array('name' => 'Cuscatancingo', 'state_id' => 6),
            array('name' => 'El Paisnal', 'state_id' => 6),
            array('name' => 'Guazapa', 'state_id' => 6),
            array('name' => 'Ilopango', 'state_id' => 6),
            array('name' => 'Mejicanos', 'state_id' => 6),
            array('name' => 'Nejapa', 'state_id' => 6),
            array('name' => 'Panchimalco', 'state_id' => 6),
            array('name' => 'Rosario de Mora', 'state_id' => 6),
            array('name' => 'San Marcos', 'state_id' => 6),
            array('name' => 'San Martín', 'state_id' => 6),
            array('name' => 'San Salvador', 'state_id' => 6),
            array('name' => 'Santiago Texacuangos', 'state_id' => 6),
            array('name' => 'Santo Tomás', 'state_id' => 6),
            array('name' => 'Soyapango', 'state_id' => 6),
            array('name' => 'Tonacatepeque', 'state_id' => 6),
            array('name' => 'Cojutepeque', 'state_id' => 7),
            array('name' => 'Candelariia', 'state_id' => 7),
            array('name' => 'El Carmen', 'state_id' => 7),
            array('name' => 'El Rosario', 'state_id' => 7),
            array('name' => 'Monte San Juan', 'state_id' => 7),
            array('name' => 'Oratorio de Concepción', 'state_id' => 7),
            array('name' => 'San Bartolomé Perulapia', 'state_id' => 7),
            array('name' => 'San Cristóbal', 'state_id' => 7),
            array('name' => 'San José Guayabal', 'state_id' => 7),
            array('name' => 'San Pedro Perulapán', 'state_id' => 7),
            array('name' => 'San Rafael Cedros', 'state_id' => 7),
            array('name' => 'San Ramón', 'state_id' => 7),
            array('name' => 'Santa Cruz Analquito', 'state_id' => 7),
            array('name' => 'Santa Cruz Michapa', 'state_id' => 7),
            array('name' => 'Suchitoto', 'state_id' => 7),
            array('name' => 'Tenancingo', 'state_id' => 7),
            array('name' => 'Zacatecoluca', 'state_id' => 8),
            array('name' => 'Cuyultitán', 'state_id' => 8),
            array('name' => 'El Rosario', 'state_id' => 8),
            array('name' => 'Jerusalén', 'state_id' => 8),
            array('name' => 'Mercedes La Ceiba', 'state_id' => 8),
            array('name' => 'Olocuilta', 'state_id' => 8),
            array('name' => 'Paraíso de Osorio', 'state_id' => 8),
            array('name' => 'San Antonio Masahuat', 'state_id' => 8),
            array('name' => 'San Emigdio', 'state_id' => 8),
            array('name' => 'San Francisco Chinameca', 'state_id' => 8),
            array('name' => 'San Pedro Masahuat', 'state_id' => 8),
            array('name' => 'San Juan Nonualco', 'state_id' => 8),
            array('name' => 'San Juan Talpa', 'state_id' => 8),
            array('name' => 'San Juan Tepezontes', 'state_id' => 8),
            array('name' => 'San Luis La Herradura', 'state_id' => 8),
            array('name' => 'San Luis Talpa', 'state_id' => 8),
            array('name' => 'San Miguel Tepezontes', 'state_id' => 8),
            array('name' => 'San Pedro Nonualco', 'state_id' => 8),
            array('name' => 'San Rafael Obrajuelo', 'state_id' => 8),
            array('name' => 'Santa María Ostuma', 'state_id' => 8),
            array('name' => 'Santiago Nonualco', 'state_id' => 8),
            array('name' => 'Tapalhuaca', 'state_id' => 8),
            array('name' => 'Apastepeque', 'state_id' => 9),
            array('name' => 'Guadalupe', 'state_id' => 9),
            array('name' => 'San Cayetano Istepeque', 'state_id' => 9),
            array('name' => 'San Esteban Catarina', 'state_id' => 9),
            array('name' => 'San Ildefonso', 'state_id' => 9),
            array('name' => 'San Lorenzo', 'state_id' => 9),
            array('name' => 'San Sebastián', 'state_id' => 9),
            array('name' => 'Santa Clara', 'state_id' => 9),
            array('name' => 'Santo Domingo', 'state_id' => 9),
            array('name' => 'Tecoluca', 'state_id' => 9),
            array('name' => 'Tepetitán', 'state_id' => 9),
            array('name' => 'Verapaz', 'state_id' => 9),
            array('name' => 'Cinquera', 'state_id' => 10),
            array('name' => 'Dolores', 'state_id' => 10),
            array('name' => 'Guacoteci', 'state_id' => 10),
            array('name' => 'Ilobasco', 'state_id' => 10),
            array('name' => 'Jutiapa', 'state_id' => 10),
            array('name' => 'San Isidro', 'state_id' => 10),
            array('name' => 'Sensuntepeque', 'state_id' => 10),
            array('name' => 'Tejutepeque', 'state_id' => 10),
            array('name' => 'Victoria', 'state_id' => 10),
            array('name' => 'Alegría', 'state_id' => 11),
            array('name' => 'Berlín', 'state_id' => 11),
            array('name' => 'California', 'state_id' => 11),
            array('name' => 'Concepción Batres', 'state_id' => 11),
            array('name' => 'El Triunfo', 'state_id' => 11),
            array('name' => 'Ereguayquín', 'state_id' => 11),
            array('name' => 'Estanzuelas', 'state_id' => 11),
            array('name' => 'Jiquilisco', 'state_id' => 11),
            array('name' => 'Jucuapa', 'state_id' => 11),
            array('name' => 'Jucuarán', 'state_id' => 11),
            array('name' => 'Mercedes Umaña', 'state_id' => 11),
            array('name' => 'Nueva Granada', 'state_id' => 11),
            array('name' => 'Ozatlán', 'state_id' => 11),
            array('name' => 'Puerto El Triunfo', 'state_id' => 11),
            array('name' => 'San Agustín', 'state_id' => 11),
            array('name' => 'San Buenaventura', 'state_id' => 11),
            array('name' => 'San Dionisio', 'state_id' => 11),
            array('name' => 'San Francisco Javier', 'state_id' => 11),
            array('name' => 'Santa Elena', 'state_id' => 11),
            array('name' => 'Santa María', 'state_id' => 11),
            array('name' => 'Santiago de María', 'state_id' => 11),
            array('name' => 'Tecapán', 'state_id' => 11),
            array('name' => 'Usulután', 'state_id' => 11),
            array('name' => 'Carolina', 'state_id' => 12),
            array('name' => 'Chapeltique', 'state_id' => 12),
            array('name' => 'Chinameca', 'state_id' => 12),
            array('name' => 'Chirilagua', 'state_id' => 12),
            array('name' => 'Ciudad Barrios', 'state_id' => 12),
            array('name' => 'Comacarán', 'state_id' => 12),
            array('name' => 'El Tránsito', 'state_id' => 12),
            array('name' => 'Lolotique', 'state_id' => 12),
            array('name' => 'Moncagua', 'state_id' => 12),
            array('name' => 'Nueva Guadalupe', 'state_id' => 12),
            array('name' => 'Nuevo Edén de San Juan', 'state_id' => 12),
            array('name' => 'Quelepa', 'state_id' => 12),
            array('name' => 'San Antonio', 'state_id' => 12),
            array('name' => 'San Gerardo', 'state_id' => 12),
            array('name' => 'San Jorge', 'state_id' => 12),
            array('name' => 'San Luis de la Reina', 'state_id' => 12),
            array('name' => 'San Miguel', 'state_id' => 12),
            array('name' => 'San Rafael Oriente', 'state_id' => 12),
            array('name' => 'Sesori', 'state_id' => 12),
            array('name' => 'Uluazapa', 'state_id' => 12),
            array('name' => 'Arambala', 'state_id' => 13),
            array('name' => 'Cacaopera', 'state_id' => 13),
            array('name' => 'Chilanga', 'state_id' => 13),
            array('name' => 'Corinto', 'state_id' => 13),
            array('name' => 'Delicias de Concepción', 'state_id' => 13),
            array('name' => 'El Divisadero', 'state_id' => 13),
            array('name' => 'El Rosario', 'state_id' => 13),
            array('name' => 'Gualococti', 'state_id' => 13),
            array('name' => 'Guatajiagua', 'state_id' => 13),
            array('name' => 'Joateca', 'state_id' => 13),
            array('name' => 'Jocoaitique', 'state_id' => 13),
            array('name' => 'Jocoro', 'state_id' => 13),
            array('name' => 'Lolotiquillo', 'state_id' => 13),
            array('name' => 'Meanguera', 'state_id' => 13),
            array('name' => 'Osicala', 'state_id' => 13),
            array('name' => 'Perquín', 'state_id' => 13),
            array('name' => 'San Carlos', 'state_id' => 13),
            array('name' => 'San Fernando', 'state_id' => 13),
            array('name' => 'San Francisco Gotera', 'state_id' => 13),
            array('name' => 'San Isidro', 'state_id' => 13),
            array('name' => 'San Simón', 'state_id' => 13),
            array('name' => 'Sensembra', 'state_id' => 13),
            array('name' => 'Sociedad', 'state_id' => 13),
            array('name' => 'Torola', 'state_id' => 13),
            array('name' => 'Yamabal', 'state_id' => 13),
            array('name' => 'Anamorós', 'state_id' => 14),
            array('name' => 'Meanguera del Golfo', 'state_id' => 14),
            array('name' => 'La Unión', 'state_id' => 14),
            array('name' => 'San Alejo', 'state_id' => 14),
            array('name' => 'Yucuaiquín', 'state_id' => 14),
            array('name' => 'Conchagua', 'state_id' => 14),
            array('name' => 'Intipucá', 'state_id' => 14),
            array('name' => 'San José', 'state_id' => 14),
            array('name' => 'El Carmen', 'state_id' => 14),
            array('name' => 'Yayantique', 'state_id' => 14),
            array('name' => 'Bolívar', 'state_id' => 14),
            array('name' => 'Concepción de Oriente', 'state_id' => 14),
            array('name' => 'El Carmen', 'state_id' => 14),
            array('name' => 'Lislique', 'state_id' => 14),
            array('name' => 'Nueva Esparta', 'state_id' => 14),
            array('name' => 'Pasaquina', 'state_id' => 14),
            array('name' => 'Polorós', 'state_id' => 14),
            array('name' => 'Meanguera del Golfo', 'state_id' => 14),
        );

		foreach ($townships as $township) {
            Township::create([
                'name' => $township['name'],
                'state_id' => $township['state_id']
            ]);
        }
    }
}
